<?php

declare (strict_types=1);
/**
 * @license Apache 2.0
 */
namespace Open_Api;

use Open_Api\Annotations as OA;
use Open_Api\Loggers\Default_Logger;
use Psr\Log\Logger_Interface;
/**
 * The context in which the annotation is parsed.
 *
 * Contexts are nested to reflect the code/parsing hierarchy. They include useful metadata
 * which the processors can use to augment the annotations.
 *
 * @property string|null                      $comment     The PHP DocComment
 * @property string|null                      $filename
 * @property int|null                         $line
 * @property int|null                         $character
 * @property string|null                      $namespace
 * @property array|null                       $uses
 * @property string|null                      $class
 * @property string|null                      $interface
 * @property string|null                      $trait
 * @property string|null                      $enum
 * @property array|string|null                $extends     Interfaces may extend a list of interfaces
 * @property array|null                       $implements
 * @property string|null                      $method
 * @property string|null                      $property
 * @property \Reflector|null                  $reflector   Optional reflection details
 * @property bool|null                        $static      Indicate a static method
 * @property bool|null                        $generated   Indicate the context was generated by a processor,
 *                                                         type resolver or serializer
 * @property OA\AbstractAnnotation|null       $nested
 * @property list<OA\AbstractAnnotation>|null $annotations
 * @property list<OA\AbstractAnnotation>|null $other       Annotations not related to OpenApi
 * @property LoggerInterface|null             $logger      Guaranteed to be set when using the <code>Generator</code>
 * @property array|null                       $scanned     Details of file scanner when using ReflectionAnalyser
 * @property string|null                      $version     The OpenAPI version in use
 */
#[\Allow_Dynamic_Properties]
class Context implements \Stringable
{
    public function __construct(
        array $properties = [],
        /**
         * Prototypical inheritance for properties.
         */
        protected ?Context $parent = null
    )
    {
        foreach ($properties as $property => $value) {
            $this->{$property} = $value;
        }
        $this->logger = $this->logger ?: new Default_Logger();
    }
    /**
     * Ensure this context is part of the context tree.
     */
    public function ensure_root(?Context $root_context): void
    {
        if ($root_context === $this) {
            return;
        }
        if (!$this->parent) {
            // use root fallback for these...
            foreach (['logger', 'version'] as $property) {
                unset($this->{$property});
            }
            $this->parent = $root_context;
        }
    }
    /**
     * Check if a property is set directly on this context and not its parent context.
     *
     * Example: $c->is('method') or $c->is('class')
     */
    public function is(string $property): bool
    {
        return property_exists($this, $property);
    }
    /**
     * Check if a property is NOT set directly on this context and its parent context.
     *
     * Example: $c->not('method') or $c->not('class')
     */
    public function not(string $property): bool
    {
        return $this->is($property) === false;
    }
    /**
     * Return the context containing the specified property.
     */
    public function with(string $property): ?Context
    {
        if ($this->is($property)) {
            return $this;
        }
        if ($this->parent instanceof Context) {
            return $this->parent->with($property);
        }
        return null;
    }
    /**
     * Get the root context.
     */
    public function root(): Context
    {
        if ($this->parent instanceof Context) {
            return $this->parent->root();
        }
        return $this;
    }
    /**
     * Get the OpenApi version.
     *
     * This is a best guess and only final once parsing is complete.
     */
    public function get_version(): string
    {
        return $this->root()->version ?: OA\Open_Api::DEFAULT_VERSION;
    }
    /**
     * Check if one of the given version numbers matches the current OpenAPI version.
     *
     * @param string|array $version The version to compare. Allows patch version placeholder `x`; e.g. `3.1.x`.
     */
    public function is_version(string|array $version): bool
    {
        foreach ((array) $version as $v) {
            if (OA\Open_Api::version_match($this->get_version(), $v)) {
                return true;
            }
        }
        return false;
    }
    /**
     * Export location for debugging.
     *
     * @return string Example: "file1.php on line 12"
     */
    public function get_debug_location(): string
    {
        $location = '';
        $fqn = $this->fully_qualified_name($this->class ?? $this->interface ?? $this->trait ?? $this->enum);
        if ($fqn && ($this->method || $this->property)) {
            $location .= $fqn;
            if ($this->method) {
                $location .= ($this->static ? '::' : '->') . $this->method . '()';
            } elseif ($this->property) {
                $location .= ($this->static ? '::$' : '->') . $this->property;
            }
        }
        if ($this->filename) {
            if ($location !== '') {
                $location .= ' in ';
            }
            $location .= $this->filename;
        }
        if ($this->line) {
            if ($location !== '') {
                $location .= ' on';
            }
            $location .= ' line ' . $this->line;
            if ($this->character) {
                $location .= ':' . $this->character;
            }
        }
        return $location;
    }
    public function __serialize(): array
    {
        return array_filter(get_object_vars($this), static function ($value): bool {
            $rc = is_object($value) ? new \ReflectionClass($value) : null;
            return (!$rc || !$rc->is_anonymous()) && !$value instanceof \Reflector && !$value instanceof \Closure;
        });
    }
    public function __unserialize(array $data): void
    {
        foreach ($data as $name => $value) {
            $this->{$name} = $value;
        }
    }
    /**
     * Traverse the context tree to get the property value.
     */
    public function __get(string $property): mixed
    {
        if ($this->parent instanceof Context) {
            return $this->parent->{$property};
        }
        return null;
    }
    public function __toString(): string
    {
        return $this->get_debug_location();
    }
    public function __debugInfo()
    {
        return ['-' => $this->get_debug_location()];
    }
    /**
     * Resolve the given `source` to a fully qualified name.
     *
     * @return class-string|null
     */
    public function fully_qualified_name(?string $source): ?string
    {
        if ($source === null) {
            return null;
        }
        $namespace = $this->namespace ? str_replace('\\\\', '\\', '\\' . $this->namespace . '\\') : '\\';
        $this_source = $this->class ?? $this->interface ?? $this->trait;
        if ($this_source && strcasecmp($source, $this_source) === 0) {
            return $namespace . $this_source;
        }
        $pos = strpos($source, '\\');
        if ($pos !== false) {
            if ($pos === 0) {
                // Fully qualified name (\Foo\Bar)
                return $source;
            }
            // Qualified name (Foo\Bar)
            if ($this->uses) {
                foreach ($this->uses as $alias => $aliased_namespace) {
                    $alias .= '\\';
                    if (strcasecmp(substr($source, 0, strlen($alias)), $alias) === 0) {
                        // Aliased namespace (use \Long\Namespace as Foo)
                        return '\\' . $aliased_namespace . substr($source, strlen($alias) - 1);
                    }
                }
            }
        } elseif ($this->uses) {
            // Unqualified name (Foo)
            foreach ($this->uses as $alias => $aliased_namespace) {
                if (strcasecmp((string) $alias, $source) === 0) {
                    return '\\' . $aliased_namespace;
                }
            }
        }
        return $namespace . $source;
    }
}